#!/usr/bin/env bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES=""
export REQUIRES

group_tests() {
  set_test_group_text "3 - Delete - Group tests" "2"
  CLASSNAME=ixbuild.resty.functional.delete.group

  # Get the ID of testgroup
  echo_test_title "Fetching group id of previously created test group"
  if [ -f /tmp/.ixbuild_test_groupid -a -s /tmp/.ixbuild_test_groupid ] ; then
    groupid=`cat /tmp/.ixbuild_test_groupid`
    echo_ok
  else
    echo_fail && return 1
  fi

  # Delete the testgroup
  echo_test_title "Delete group: testgroup/newgroup"
  rest_request "DELETE" "/account/groups/${groupid}/"
  check_rest_response "204"


}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
group_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) group_tests ;;
     COMPLETE) group_tests ;;
    BENCHMARK) ;;
            *) group_tests ;;
  esac
}
