#!/usr/bin/env bash
# Author: Kris Moore
# License: BSD
# Location for tests into REST API of FreeNAS
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES=""
export REQUIRES

iscsi_tests()
{
  local MOUNTPOINT="/tmp/${BRIDGEHOST}iscsi"
  local DEVICE_NAME_PATH="/tmp/iscsi_dev_name"
  local TARGET_NAME="iqn.${BUILDTAG}:target0"

  # Set the group text and number of tests
  set_test_group_text "3 - Delete - iSCSI tests" "2"
  CLASSNAME=ixbuild.resty.functional.delete.iscsi

  # TODO - Find correct process name on test executor
  # bsd_test "ps -aux | grep -q \"[i]scsid\""
  # if [ $? -ne 0 ]; then
  #   echo -n "iSCSI service does not appear to be running."
  #   echo_skipped
  #   return 0
  # fi

  # Clean up any leftover items from any previous failed runs
  rest_request "PUT" "/services/services/iscsitarget/" '{ "srv_enable": "false" }'
  if [ -n "$BSD_HOST" -o -n "$BSD_USERNAME" ] ; then
    bsd_test "iscsictl -R -t ${TARGET_NAME}"
    bsd_test "umount -f \"${MOUNTPOINT}\" &>/dev/null ; rmdir \"${MOUNTPOINT}\" &>/dev/null"
  fi

  # Remove iSCSI target
  echo_test_title "Delete iSCSI target"
  rest_request "DELETE" "/services/iscsi/target/1/"
  check_rest_response "204"

  # Remove iSCSI extent
  echo_test_title "Delete iSCSI extent"
  rest_request "DELETE" "/services/iscsi/extent/1/"
  check_rest_response "204"

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
iscsi_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) iscsi_tests ;;
     COMPLETE) iscsi_tests ;;
    BENCHMARK) ;;
            *) iscsi_tests ;;
  esac
}
