#!/usr/local/bin/bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES=""
export REQUIRES

rsync_tests() {
  set_test_group_text "3 - Delete - RSYNC tests" "1"

  echo_test_title "Delete rsync resource"
  rest_request "DELETE" "/services/rsyncmod/1/"
  check_rest_response "204"

}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
rsync_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) rsync_tests ;;
     COMPLETE) rsync_tests ;;
    BENCHMARK) ;;
            *) rsync_tests ;;
  esac
}
