#!/usr/local/bin/bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="user group rsync"
export REQUIRES

storage_tests()
{
  # Set the group text and number of tests
  set_test_group_text "3 - Delete - Storage tests" "4"

  # Check destroying a ZFS snapshot
  echo_test_title "Destroying ZFS snapshot tank@test"
  rest_request "DELETE" "/storage/snapshot/tank/test/"
  check_rest_response "204" || return 1

  # Check destroying a ZVOL
  echo_test_title "Destroying ZVOL"
  rest_request "DELETE" "storage/volume/tank/zvols/testzvol/"
  check_rest_response "204" || return 1

  # Check destroying a dataset
  echo_test_title "Destroying dataset"
  rest_request "DELETE" "/storage/volume/1/datasets/cifs/"
  check_rest_response "204" || return 1

  # Check destroying a zpool
  echo_test_title "Destroying volume"
  rest_request "DELETE" "/storage/volume/1/"
  check_rest_response "204" || return 1

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
storage_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) storage_tests ; return $? ;;
     COMPLETE) storage_tests ; return $? ;;
    BENCHMARK) storage_tests ; return $? ;;
            *) storage_tests ; return $? ;;
  esac
}
