#!/usr/local/bin/bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="user group rsync storage"
export REQUIRES

system_tests()
{
  # Set the group text and number of tests
  set_test_group_text "4 - Factory system test" "1"

  echo_test_title "Restoring to factory defaults"
  rest_request "POST" "/system/config/factory_system/"
  check_rest_response "202" || return 1

}

# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
system_init()
{
  # Run all the system tests
  case $TESTSET in
        SMOKE) system_tests ; return $? ;;
     COMPLETE) system_tests ; return $? ;;
    BENCHMARK) system_tests ; return $? ;;
            *) system_tests ; return $? ;;
  esac
}
