#!/usr/local/bin/bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES=""
export REQUIRES

user_tests() {
  set_test_group_text "Delete User tests" "1"

  # Delete the testuser
  echo_test_title "Deleting user: testuser"
  rest_request "DELETE" "/account/users/28"
  check_rest_response "204"

}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
user_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) user_tests ;;
     COMPLETE) user_tests ;;
    BENCHMARK) ;;
            *) user_tests ;;
  esac
}
