#############################################################################
# Makefile for building: PCBSD
#############################################################################

####### Install

image:
	@cd ${.CURDIR}/scripts/ && sh build-iso.sh iso
iso:
	@cd ${.CURDIR}/scripts/ && sh build-iso.sh iso
