#!/usr/local/bin/bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="system volume dataset"
export REQUIRES

account_tests()
{
  # Set the group text and number of tests
  set_test_group_text "1 - account tests" "1"
  CLASSNAME=ixbuild.resty.functional.account

  if [ -z "$FNASTESTIP" ] ; then
     echo "Missing the FNASTESTIP settings, test skipped.."
     echo_skipped
     add_xml_result "skipped" "Skipped due to missing FNASTESTIP settings"
     return 0
  fi

  echo_test_title "Check creating account for qa.."
  ssh_test 'cli -e "account user create qa set password=abcd1234"'
  check_exit_status || return 1

  sleep 5

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
account_init()
{
  # Run all the account tests
  case $TESTSET in
        SMOKE) account_tests ; return $? ;;
     COMPLETE) account_tests ; return $? ;;
    BENCHMARK) account_tests ; return $? ;;
            *) account_tests ; return $? ;;
  esac
}
