#!/usr/local/bin/bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="system volume dataset account"
export REQUIRES

smb_tests()
{
  # Set the group text and number of tests
  set_test_group_text "1 - smb tests" "5"
  CLASSNAME=ixbuild.resty.functional.smb

  if [ -z "$FNASTESTIP" ] ; then
     echo "Missing the FNASTESTIP settings, test skipped.."
     echo_skipped
     add_xml_result "skipped" "Skipped due to missing FNASTESTIP settings"
     return 0
  fi

  echo_test_title "Check creating smb share.."
  ssh_test 'cli -e "share smb create smbshare dataset=tank/smbshare"'
  check_exit_status || return 1

  sleep 5

  echo_test_title "Allow guest to smb share.."
  ssh_test 'cli -e "share smb smbshare set guest_ok=yes"'
  check_exit_status || return 1

  sleep 5

  echo_test_title "Change smb share owner to qa.."
  ssh_test 'cli -e "share smb smbshare set owner=qa"'
  check_exit_status || return 1

  sleep 5

  echo_test_title "Enable smb service.."
  ssh_test 'cli -e "service smb config set enable=yes"'
  check_exit_status || return 1 

  sleep 5

  echo_test_title "Start smb service.."
  ssh_test 'cli -e "cli -e service smb start"'
  check_exit_status || return 1

  sleep 5

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
smb_init()
{
  # Run all the smb tests
  case $TESTSET in
        SMOKE) smb_tests ; return $? ;;
     COMPLETE) smb_tests ; return $? ;;
    BENCHMARK) smb_tests ; return $? ;;
            *) smb_tests ; return $? ;;
  esac
}
