#!/usr/local/bin/bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="system"
export REQUIRES

volume_tests()
{
  # Set the group text and number of tests
  set_test_group_text "1 - volume tests" "1"
  CLASSNAME=ixbuild.resty.functional.volume

  if [ -z "$FNASTESTIP" ] ; then
     echo "Missing the FNASTESTIP settings, test skipped.."
     echo_skipped
     add_xml_result "skipped" "Skipped due to missing FNASTESTIP settings"
     return 0
  fi

  echo_test_title "Check creating volume.."
  ssh_test 'cli -e "volume create tank disks=ada1,ada2"'
  check_exit_status || return 1

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
volume_init()
{
  # Run all the volume tests
  case $TESTSET in
        SMOKE) volume_tests ; return $? ;;
     COMPLETE) volume_tests ; return $? ;;
    BENCHMARK) volume_tests ; return $? ;;
            *) volume_tests ; return $? ;;
  esac
}
