#!/usr/local/bin/bash
# Author: Kris Moore
# License: BSD
# Location for tests into REST API of FreeNAS 9.3
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES=""
export REQUIRES

# Run a series of tests on the boot-environments
debug_tests() {
  set_test_group_text "Debugging Tests" "1"

  echo_test_title "Creating diagnostic file"
  POST /system/debug/ '{ "name": "newbe1", "source": "default" }' -v >${RESTYOUT} 2>${RESTYERR}
  check_rest_response "200 OK"
  echo_ok

  # Get the URL of the debug file
  dlurl=$(cat ${RESTYOUT} | ${JSAWK} 'return this.url')
  echo "Debug URL: http://${ip}$dlurl"
  # KPM - 02-05-2016 - Need to figure out magic to do login + fetch
  #fetch -o /tmp/debug.tgz http://${io}${durl}
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
debug_init()
{
  # Run all the debug tests
  case $TESTSET in
        SMOKE) debug_tests ;;
     COMPLETE) debug_tests ;;
    BENCHMARK) ;;
            *) debug_tests ;;
  esac
}

