#!/usr/local/bin/bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS 9.3
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="storage"
export REQUIRES

ad_tests() {
  set_test_group_text "Active Directory tests" "1"

  if [ -z "$ADUSERNAME" -o -z "$ADPASSWORD" -o -z "$ADREALM" ] ; then
     echo "Missing the ADUSERNAME / ADPASSWORD / ADREALM settings, test skipped.."
     echo_skipped
     add_xml_result "skipped" "Skipped due to missing AD settings"
     return 0
  fi


  # Join the Active Directory
  echo_test_title "Updating Settings for AD.."
  rest_request "PUT" "/directoryservice/activedirectory/" '{ "ad_bindpw": "'${ADPASSWORD}'", "ad_bindname": "'${ADUSERNAME}'", "ad_domainname": 
"'${ADREALM'" }'
  check_rest_response "200 OK" || return 1

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
ad_init()
{
  # Run all the tests
  case $TESTSET in
        SMOKE) ad_tests ; return $? ;;
     COMPLETE) ad_tests ; return $? ;;
    BENCHMARK) ;;
            *) ad_tests ; return $? ;;
  esac
}
