#!/usr/local/bin/bash
# Author: Kris Moore
# License: BSD
# Location for tests into REST API of FreeNAS 9.3
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="storage"
export REQUIRES

nfs_tests()
{
  # Set the group text and number of tests
  set_test_group_text "NFS tests" "12"

  # Enable NFS server
  echo_test_title "Creating the NFS server"
  rest_request "PUT" "/services/nfs/" '{ "nfs_srv_bindip": "'"${ip}"'", "nfs_srv_mountd_port": 618, "nfs_srv_allow_nonroot": false, "nfs_srv_servers": 10, "nfs_srv_udp": false, "nfs_srv_rpcstatd_port": 871, "nfs_srv_rpclockd_port": 32803, "nfs_srv_v4": false, "nfs_srv_v4_krb": false, "id": 1 }'
  check_rest_response "200 OK"

  # Check creating a NFS share
  echo_test_title "Creating a NFS share on /mnt/tank/share"
  rest_request "POST" "/sharing/nfs/" '{ "nfs_comment": "My Test Share", "nfs_paths": ["/mnt/tank/share"], "nfs_security": "sys" }'
  check_rest_response "201 CREATED"

  # Now start the service
  echo_test_title "Starting NFS service"
  rest_request "PUT" "/services/services/nfs/" '{ "srv_enable": true }'
  check_rest_response "200 OK"

  # Now check if we can mount NFS / create / rename / copy / delete / umount
  echo_test_title "Creating NFS mountpoint"
  rc_test "mkdir /tmp/nfs-mnt.$$" || return 1

  echo_test_title "Mounting NFS"
  rc_test "mount_nfs ${ip}:/mnt/tank/share /tmp/nfs-mnt.$$" "umount /tmp/nfs-mnt.$$ ; rmdir /tmp/nfs-mnt.$$" "60" || return 1

  echo_test_title "Creating NFS file"
  rc_test "touch /tmp/nfs-mnt.$$/testfile" "umount /tmp/nfs-mnt.$$ ; rmdir /tmp/nfs-mnt.$$" || return 1

  echo_test_title "Moving NFS file"
  rc_test "mv /tmp/nfs-mnt.$$/testfile /tmp/nfs-mnt.$$/testfile2" || return 1

  echo_test_title "Copying NFS file"
  rc_test "cp /tmp/nfs-mnt.$$/testfile2 /tmp/nfs-mnt.$$/testfile" || return 1

  echo_test_title "Deleting NFS file"
  rc_test "rm /tmp/nfs-mnt.$$/testfile2" || return 1

  echo_test_title "Unmounting NFS"
  rc_test "umount /tmp/nfs-mnt.$$" || return 1

  echo_test_title "Removing NFS mountpoint"
  rc_test "rmdir /tmp/nfs-mnt.$$" || return 1
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
nfs_init()
{
  # Run all the nfs tests
  case $TESTSET in
        SMOKE) nfs_tests ;;
     COMPLETE) nfs_tests ;;
    BENCHMARK) ;;
            *) nfs_tests ;;
  esac
}

