#!/usr/local/bin/bash
# Author: Kris Moore
# License: BSD
# Location for tests into REST API of FreeNAS 9.3
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="storage"
export REQUIRES

rsync_tests() {
  set_test_group_text "RSYNC tests" "4"

  echo_test_title "Configuring rsyncd service"
  PUT /services/rsyncd/ '{ "rsyncd_port": 873 }' -v >${RESTYOUT} 2>${RESTYERR}
  check_rest_response "200 OK"
  echo_ok

  echo_test_title "Starting rsyncd service"
  PUT /services/services/rsync/ '{ "srv_enable": true }' -v >${RESTYOUT} 2>${RESTYERR}
  check_rest_response "200 OK"
  echo_ok

  echo_test_title "Creating rsync resource"
  POST /services/rsyncmod/ '{ "rsyncmod_name": "testmod", "rsyncmod_path": "/mnt/tank/share" }' -v >${RESTYOUT} 2>${RESTYERR}
  check_rest_response "201 CREATED"
  echo_ok

  # Test rsync
  echo_test_title "Testing rsync access"
  rc_halt "rsync -avn ${ip}::testmod"
  echo_ok
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
rsync_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) rsync_tests ;;
     COMPLETE) rsync_tests ;;
    BENCHMARK) ;;
            *) rsync_tests ;;
  esac
}
