#!/usr/local/bin/bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS 9.3
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="storage ssh smb nfs iscsi"
export REQUIRES

ha_tests()
{
  # Set the group text and number of tests
  set_test_group_text "High Availability tests" "4"

  # Simulate HA Panic
  trigger_ha_failover "panic"
  echo_ok

  # Check HA Status
  do_ha_status

  # Simulate HA Reboot
  trigger_ha_failover "reboot"
  echo_ok

  # Check HA Status
  do_ha_status

}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
ha_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) ha_tests ;;
     COMPLETE) ha_tests ;;
    BENCHMARK) ;;
            *) ha_tests ;;
  esac
}
