#!/usr/local/bin/bash
# Author: Kris Moore
# License: BSD
# Location for tests into REST API of FreeNAS 9.3
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="storage"
export REQUIRES

iscsi_tests()
{
  # Set the group text and number of tests
  set_test_group_text "iSCSI tests" "2"

  # Check to see if iSCSI service is running
  echo_test_title "Checking to see if iSCSI service is enabled"
  rest_request "GET" "/services/services/iscsitarget/"
  check_rest_response "200 OK" || return 1
  ISCSISTATUS=$(cat ${RESTYOUT} | ${JSAWK} 'return this.srv_enable')
  echo "ISCSISTATUS: $ISCSISTATUS"
  echo $ISCSISTATUS | grep -q 'true'
  if [ $? -eq 0 ] ; then
    echo_ok
  else

    # Now start the service
    echo_test_title "Starting iSCSI service"
    rest_request "PUT" "/services/services/iscsitarget/" '{ "srv_enable": true }'
    check_rest_response "200 OK"

    echo_ok
  fi

}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
iscsi_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) iscsi_tests ;;
     COMPLETE) iscsi_tests ;;
    BENCHMARK) ;;
            *) iscsi_tests ;;
  esac
}
