#!/usr/local/bin/bash
# Author: Kris Moore
# License: BSD
# Location for tests into REST API of FreeNAS 9.3
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="storage"
export REQUIRES

nfs_tests()
{
  # Set the group text and number of tests
  set_test_group_text "NFS tests" "12"

  # TODO
  # 
  # Write series of tests to do the following:
  # 
  # Check if an NFS share is created and service started
  # If NOT, then provision the node 
  #
  # If services exist, use existing
  #


}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
nfs_init()
{
  # Run all the nfs tests
  case $TESTSET in
        SMOKE) nfs_tests ;;
     COMPLETE) nfs_tests ;;
    BENCHMARK) ;;
            *) nfs_tests ;;
  esac
}

