#!/usr/bin/env bash
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="storage"
export REQUIRES

alerts_tests()
{
  ALERT_MSG="Testing system alerts with failure."
  ALERT_STATUS="FAIL"
  ALERTS_FILE="/tmp/self-test-alert"

  set_test_group_text "1 - Create - System Alert tests" "1"
  CLASSNAME=ixbuild.resty.functional.create.alerts

  echo_test_title "Create an alert on the remote system"
  ssh_test "echo '[${ALERT_STATUS}] ${ALERT_MSG}' >> '${ALERTS_FILE}'"
  check_exit_status || return 1

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
alerts_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) alerts_tests ;;
     COMPLETE) alerts_tests ;;
    BENCHMARK) ;;
            *) alerts_tests ;;
  esac
}
