#!/usr/bin/env bash
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="storage"
export REQUIRES

cronjob_tests()
{
  set_test_group_text "1 - Create - Cron tests" "2"
  CLASSNAME=ixbuild.resty.functional.create.cronjob

  local TESTFILE="/tmp/.testFileCreatedViaCronjob"

  echo_test_title "Creating new cron job which will run every minute"
  rest_request "POST" "/tasks/cronjob/" '{ "cron_user": "root", "cron_command": "touch '${TESTFILE}'", "cron_minute": "*/1" }'
  check_rest_response "201 Created" || return 1

  echo_test_title "Checking to see if cronjob was created and enabled"
  rest_request "GET" "/tasks/cronjob/"
  check_property_value ".[].cron_enabled" "true" || return 1

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
cronjob_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) cronjob_tests ;;
     COMPLETE) cronjob_tests ;;
    BENCHMARK) ;;
            *) cronjob_tests ;;
  esac
}
