#!/usr/local/bin/bash
# Author: Kris Moore
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES=""
export REQUIRES

# Run a series of tests on the boot-environments
debug_tests()
{
  set_test_group_text "1 - Create - Debugging Tests" "3"
  CLASSNAME=ixbuild.resty.functional.create.debug

  echo_test_title "Creating diagnostic file"
  rest_request "POST" "/system/debug/" '{ "name": "newbe1", "source": "default" }'
  check_rest_response "200 OK" || return 1

  echo_test_title "Verify that API returns WWW download path"
  check_property_value "this.url" "/system/debug/download/" || return 1

  # Currently there is no way to create an authenticated session with FreeNAS
  # WWW via the API, so fetch file with SCP and the expected path. CD - 03/24/17
  echo_test_title "Fetch debug file from URL"
  scp_from_test "/var/db/system/ixdiagnose/ixdiagnose.tgz" "/tmp/${VM}debug.tgz"
  check_exit_status || return 1

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
debug_init()
{
  # Run all the debug tests
  case $TESTSET in
        SMOKE) debug_tests ; return $? ;;
     COMPLETE) debug_tests ; return $? ;;
    BENCHMARK) ;;
            *) debug_tests ; return $? ;;
  esac
}

