#!/usr/local/bin/bash
# Author: Kris Moore
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="storage"
export REQUIRES

example_tests()
{
  # Set the group text and number of tests
  set_test_group_text "1 - Create - Example test class" "2"

  echo_test_title "Example test"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
  check_rest_response "201 Created" || return 1

  # Tests all passed!
  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
example_init()
{
  # Run all the tests
  case $TESTSET in
        SMOKE) example_tests ; return $? ;;
     COMPLETE) example_tests ; return $? ;;
    BENCHMARK) ;;
            *) example_tests ; return $? ;;
  esac
}

