#!/usr/local/bin/bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="storage"
export REQUIRES

group_tests() {
  set_test_group_text "1 - Create - Group tests" "2"
  CLASSNAME=ixbuild.resty.functional.create

  # Create the testgroup
  echo_test_title "Creating group: testgroup"
  rest_request "POST" "/account/groups/" '{ "bsdgrp_gid": 1200,"bsdgrp_group": "testgroup" }'
  check_rest_response "201 Created"

  # Get the ID of this group
  groupid=$(cat ${RESTYOUT} | ${JSAWK} 'return this.id')

  # Create temporary directory for output if needed
  if [ ! -d "${FNASBDIR}" ] ; then
  mkdir "${FNASBDIR}"
  fi

  # Save the ID of this group for other jobs
  echo $groupid > ${FNASBDIR}/testgroup

}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
group_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) group_tests ;;
     COMPLETE) group_tests ;;
    BENCHMARK) ;;
            *) group_tests ;;
  esac
}
