#!/usr/local/bin/bash
# Author: Kris Moore
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="storage"
export REQUIRES

# Run a series of tests on jail creation
jail_tests() {
  set_test_group_text "1 - Create - Jail Tests" "6"

 if [ -z "$JAILIP" -o -z "$JAILNETMASK" ] ; then
     echo "Missing the JAILIP / JAILNETMASK settings, test skipped.."
     echo_skipped
     add_xml_result "skipped" "Skipped due to missing jail settings"
     return 0
  fi

  echo_test_title "Configuring jails"
  rest_request "PUT" "/jails/configuration/" '{ "jc_ipv4_network_start": "${JAILIP}", "jc_path": "/mnt/tank/jails" }'
  check_rest_response "201 CREATED"

  echo_test_title "Creating jail - VNET OFF"
  rest_request "POST" "/jails/jails/" '{ "jail_host": "testjail", "jail_defaultrouter_ipv4": "${JAILGW}", "jail_ipv4": "${JAILIP}", "jail_ipv4_netmask": "${JAILNETMASK}", "jail_vnet": false }'
  check_rest_response "201 CREATED"

  echo_test_title "Mount tank/share into jail"
  rest_request "POST" "/jails/mountpoints/" '{ "destination": "/mnt", "jail": "testjail", "mounted": true, "readonly": false, "source": "/mnt/tank/share" }'
  check_rest_response "201 CREATED"

  echo_test_title "Starting jail"
  rest_request "POST" "/jails/jails/1/start/" ''
  check_rest_response "202 ACCEPTED"

  echo_test_title "Restarting jail"
  rest_request "POST" "/jails/jails/1/restart/" ''
  check_rest_response "202 ACCEPTED"

  echo_test_title "Stopping jail"
  rest_request "POST" "/jails/jails/1/stop/" ''
  check_rest_response "202 ACCEPTED"
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
jail_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) jail_tests ;;
     COMPLETE) jail_tests ;;
    BENCHMARK) ;;
            *) jail_tests ;;
  esac
}
