#!/usr/bin/env bash
# Author: Kris Moore
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="storage"
export REQUIRES

ldap_nfs_tests()
{
  local DATASET="ldap-nfs"
  local NFS_PATH="/mnt/tank/${DATASET}"
  local MOUNTPOINT="/tmp/nfs-mnt.$$"
  local NFS_HOST=${ip}
  local NFS_PORT=618
  local MP_GROUP="some thing"

  if [ -z "${NFS_HOST}" ]; then
    if [ -n "${BRIDGEIP}" ]; then
      NFS_HOST=${BRIDGEIP}
    elif [ -n "${FNASTESTIP}" ]; then
      NFS_HOST=${FNASTESTIP}
    fi
  fi

  # Set the group text and number of tests
  set_test_group_text "1 - Create - LDAP NFS tests" "24"
  CLASSNAME=ixbuild.resty.functional.create.ldap_nfs

  local REQUIRED_SETTINGS=( "LDAPHOSTNAME" "LDAPBINDDN" "LDAPBINDPASSWORD" )
  for SETTING in "${REQUIRED_SETTINGS[@]}"
  do
    if [ -z "${!SETTING}" ]; then
      echo -n "Required settings for webdav_osx: '${REQUIRED_SETTINGS[*]}'; missing ${SETTING}"
      echo_skipped
      return 0
    fi
  done

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
ldap_nfs_init()
{
  # Run all the nfs tests
  case $TESTSET in
        SMOKE) ldap_nfs_tests ;;
     COMPLETE) ldap_nfs_tests ;;
    BENCHMARK) ;;
            *) ldap_nfs_tests ;;
  esac
}

