#!/usr/bin/env bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES=""
export REQUIRES

network_tests()
{
  local TEST_CNT=1
  local  IFACE="vtnet0"

  # Set the group text and number of tests
  set_test_group_text "1 - Create - Network tests" "${TEST_CNT}"
  CLASSNAME=ixbuild.resty.functional.create.network

  if [ -z "$FNASTESTIP" ] ; then
     echo "Missing the FNASTESTIP settings, test skipped.."
     echo_skipped
     add_xml_result "skipped" "Skipped due to missing FNASTESTIP settings"
     return 0
  fi

  # Configure interface for DHCP
  echo_test_title "Setting DHCP on vtnet0"
  rest_request "POST" "/network/interface/" '{ "int_dhcp": true, "int_name": "ext", "int_interface": "'${IFACE}'" }'
  check_rest_response "201 Created"

}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
network_init()
{
  # Run all the tests
  case $TESTSET in
        SMOKE) network_tests ; return $? ;;
     COMPLETE) network_tests ; return $? ;;
    BENCHMARK) ;;
            *) network_tests ; return $? ;;
  esac
}
