#!/usr/local/bin/bash
# Author: Kris Moore
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="storage"
export REQUIRES

rsync_tests() {
  set_test_group_text "1 - Create - RSYNC tests" "5"
  CLASSNAME=ixbuild.resty.functional.create.rsync

  echo_test_title "Configuring rsyncd service"
  rest_request "PUT" "/services/rsyncd/" '{ "rsyncd_port": 873 }'
  check_rest_response "200 OK"

  echo_test_title "Starting rsyncd service"
  rest_request "PUT" "/services/services/rsync/" '{ "srv_enable": true }'
  check_rest_response "200 OK"

  echo_test_title "Checking to see if rsync service is enabled"
  rest_request "GET" "/services/services/rsync/"
  check_rest_response "200 OK" || return 1  
  RSYNCSTATUS=$(cat ${RESTYOUT} | ${JSAWK} 'return this.srv_state')
  echo "RSYNCSTATUS: $RSYNCSTATUS"
  echo $RSYNCSTATUS | grep -q 'RUNNING'
  if [ $? -eq 0 ] ; then
    echo_ok
  else
    echo_fail
  fi

  echo_test_title "Creating rsync resource"
  rest_request "POST" "/services/rsyncmod/" '{ "rsyncmod_name": "testmod", "rsyncmod_path": "/mnt/tank/share" }'
  check_rest_response "201 Created"

  # Test rsync
  echo_test_title "Testing rsync access"
  rc_test "rsync -avn ${ip}::testmod" || return 1
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
rsync_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) rsync_tests ;;
     COMPLETE) rsync_tests ;;
    BENCHMARK) ;;
            *) rsync_tests ;;
  esac
}
