#!/usr/bin/env bash
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="storage"
export REQUIRES

smarttest_tests()
{
  TEST_CNT=2

  # Set the group text and number of tests
  set_test_group_text "1 - Create - SMARTTest tests" "${TEST_CNT}"
  CLASSNAME=ixbuild.resty.functional.create.smarttest

  # Get list of disk_identifiers from /storage/disks
  rest_request "GET" "/storage/disk"
  local disk_identifiers=`cat ${RESTYOUT} | jq '.disk_identifier'`
  local disk_ident_1=`echo ${disk_identifiers} | cut -d " " -f1`

  echo_test_title "Create a new SMARTTest"
  rest_request "POST" "/tasks/smarttest/" '{ "smarttest_disks": "'${disk_ident_1}'", "smarttest_type": "L", "smarttest_hour": "*", "smarttest_daymonth": "*", "smarttest_month": "*", "smarttest_dayweek": "*" }'
  check_rest_response "201" || return 1

  echo_test_title "Check that API reports new SMARTTest"
  rest_request "GET" "/tasks/smarttest/"
  check_property_value ".[].smarttest_disks" "${disk_ident_1}"

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
smarttest_init()
{
  # Run all the SMARTTest tests
  case $TESTSET in
        SMOKE) smarttest_tests ;;
     COMPLETE) smarttest_tests ;;
    BENCHMARK) ;;
            *) smarttest_tests ;;
  esac
}
