#!/usr/bin/env bash
# Author: Kris Moore
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="storage"
export REQUIRES

smb_osx_tests()
{
  local DATASET="smb-osx"
  local SMB_NAME="TestShare"
  local SMB_PATH="/mnt/tank/${DATASET}"
  local MOUNTPOINT="/Volumes/${BRIDGEHOST}"
  local MP_GROUP="wheel"

  TEST_CNT=13
  if [ -n "${OSX_HOST}" -a -n "${BRIDGEIP}" ]; then
    TEST_CNT=21

    # Clean up any leftover items from previous failed SMB runs
    osx_test -q "umount -f '${MOUNTPOINT}'; rmdir '${MOUNTPOINT}'; exit 0;"
  fi
    
  # Set the group text and number of tests
  set_test_group_text "1 - Create - Samba OS X tests" "${TEST_CNT}"
  CLASSNAME=ixbuild.resty.functional.create.smb_osx

  # Clean up any leftover items from previous failed AD LDAP or SMB runs
  rest_request "PUT" "/directoryservice/activedirectory/1/" '{ "ad_bindpw": "'${ADPASSWORD}'", "ad_bindname": "'${ADUSERNAME}'", "ad_domainname": "'${BRIDGEDOMAIN}'", "ad_netbiosname_a": "'${BRIDGEHOST}'", "ad_idmap_backend": "rid", "ad_enable":"false" }'
  rest_request "PUT" "/directoryservice/ldap/1/" '{ "ldap_basedn": "'${LDAPBASEDN}'", "ldap_binddn": "'${LDAPBINDDN}'",  "ldap_bindpw": "'${LDAPBINDPASSWORD}'", "ldap_netbiosname_a": "'${BRIDGEHOST}'", "ldap_hostname": "'${LDAPHOSTNAME}'", "ldap_has_samba_schema": true, "ldap_enable": false }'
  rest_request "PUT" "/services/services/cifs/" '{ "srv_enable": false }'
  rest_request "DELETE" "/sharing/cifs/" '{ "cfs_comment": "My Test SMB Share", "cifs_path": "'"${SMB_PATH}"'", "cifs_name": "'"${SMB_NAME}"'", "cifs_guestok": true, "cifs_vfsobjects": "streams_xattr" }'
  rest_request "DELETE" "/storage/volume/1/datasets/${DATASET}/"

  # Set auxilary parameters to allow mount_smbfs to work with ldap
  echo_test_title "Setting auxilary parameters for mount_smbfs.."
  rest_request "PUT" "/services/cifs/" '{ "cifs_srv_smb_options": "lanman auth = no\nntlm auth = no \nraw NTLMv2 auth = no" }'
  check_rest_response "200 OK"

  echo_test_title "Creating SMB dataset"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "'"${DATASET}"'" }'
  check_rest_response "201 Created"

  echo_test_title "Starting SMB service"
  rest_request "PUT" "/services/services/cifs/" '{ "srv_enable": true }'
  check_rest_response "200 OK"

  echo_test_title "Changing permissions on ${SMB_PATH}"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "'"${SMB_PATH}"'", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "'${MP_GROUP}'" }'
  check_rest_response "201 Created"

  echo_test_title "Creating a SMB share on ${SMB_PATH}"
  rest_request "POST" "/sharing/cifs/" '{ "cfs_comment": "My Test SMB Share", "cifs_path": "'"${SMB_PATH}"'", "cifs_name": "'"${SMB_NAME}"'", "cifs_guestok": true, "cifs_vfsobjects": "streams_xattr" }'
  check_rest_response "201 Created"

  echo_test_title "Poll VM to ensure SMB service is up and running"
  wait_for_avail_port "445"
  check_exit_status || return 1

  echo_test_title "Checking to see if SMB service is enabled"
  rest_request "GET" "/services/services/cifs/"
  check_service_status "RUNNING" || return 1

  echo_test_title "Checking permissions on ${SMB_PATH}"
  check_dataset_group "${SMB_PATH}" "${MP_GROUP}" || return 1

  if [ -n "${OSX_HOST}" -a -n "${BRIDGEIP}" ]; then
    # Mount share on OSX system and create a test file
    echo_test_title "Create mount-point for SMB on OSX system"
    osx_test "mkdir -p '${MOUNTPOINT}' && sync" || return 1

    echo_test_title "Mount SMB share on OSX system"
    osx_test "mount -t smbfs 'smb://guest@${BRIDGEIP}/${SMB_NAME}' '${MOUNTPOINT}' && sync" || return 1

    echo_test_title "Verify SMB share has been mounted on OSX"
    wait_for_osx_mnt "${MOUNTPOINT}"
    check_exit_status || return 1

    echo_test_title "Checking for ability to list files on ${MOUNTPOINT}"
    osx_test "time ls -la \"${MOUNTPOINT}\"" || return 1

    echo_test_title "Create file on SMB share via OSX to test permissions"
    osx_test "touch '${MOUNTPOINT}/testfile.txt'" || return 1

    # Move test file to a new location on the SMB share
    echo_test_title "Moving SMB test file into a new directory"
    osx_test "mkdir -p '${MOUNTPOINT}/tmp' && mv '${MOUNTPOINT}/testfile.txt' '${MOUNTPOINT}/tmp/testfile.txt'" || return 1

    # Delete test file and test directory from SMB share
    echo_test_title "Deleting test file and directory from SMB share"
    osx_test "rm -f '${MOUNTPOINT}/tmp/testfile.txt' && rmdir '${MOUNTPOINT}/tmp'" || return 1

    echo_test_title "Verifying that test file and directory were successfully removed"
    osx_test "find -- '${MOUNTPOINT}/' -prune -type d -empty | grep -q ." || return 1

    # Clean up mounted SMB share
    echo_test_title "Unmount SMB share"
    osx_test "umount -f '${MOUNTPOINT}'" || return 1
  fi

  echo_test_title "Removing SMB share on ${SMB_PATH}"
  rest_request "DELETE" "/sharing/cifs/" '{ "cfs_comment": "My Test SMB Share", "cifs_path": "'"${SMB_PATH}"'", "cifs_name": "'"${SMB_NAME}"'", "cifs_guestok": true, "cifs_vfsobjects": "streams_xattr" }'
  check_rest_response "204"

  # Now stop the service
  echo_test_title "Stopping SMB service"
  rest_request "PUT" "/services/services/cifs/" '{ "srv_enable": false }'
  check_rest_response "200 OK" || return 1

  echo_test_title "Verify SMB service is disabled"
  rest_request "GET" "/services/services/cifs/"
  check_service_status "STOPPED"

  # Check destroying a SMB dataset
  echo_test_title "Destroying SMB dataset"
  rest_request "DELETE" "/storage/volume/1/datasets/${DATASET}/"
  check_rest_response "204" || return 1

  return 0

}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
smb_osx_init()
{
  # Run all the smb_osx tests
  case $TESTSET in
        SMOKE) smb_osx_tests ;;
     COMPLETE) smb_osx_tests ;;
    BENCHMARK) ;;
            *) smb_osx_tests ;;
  esac
}
