#!/usr/bin/env bash
# License: BSD
# Location for tests into REST API of FreeNAS
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="storage"
export REQUIRES

snmp_tests()
{
  COMMUNITY="public"
  TRAPS=false
  CONTACT="root@localhost"
  LOCATION="Maryville, TN"
  PASSWORD="testing1234"

  set_test_group_text "1 - Create - SNMP tests" "4"
  CLASSNAME=ixbuild.resty.functional.create.snmp

  echo_test_title "Configure SNMP"
  rest_request "PUT" "/services/snmp/" '{ "snmp_community": "'"${COMMUNITY}"'", "snmp_traps": '${TRAPS}', "snmp_contact": "'"${CONTACT}"'", "snmp_location": "'"${LOCATION}"'", "snmp_v3_password": "'"${PASSWORD}"'", "snmp_v3_password2": "'"${PASSWORD}"'" }'
  check_rest_response "200"

  echo_test_title "Enable SNMP service"
  rest_request "PUT" "/services/services/snmp/" '{ "srv_enable": true }'
  check_rest_response "200"

  echo_test_title "Validate that SNMP service is running"
  rest_request "GET" "/services/services/snmp/"
  check_service_status "RUNNING" || return 1

  echo_test_title "Validate that SNMP settings were preserved"
  rest_request "GET" "/services/snmp/"
  check_property_value -q "this.snmp_community" "${COMMUNITY}" \
    && check_property_value -q "this.snmp_traps" "${TRAPS}" \
    && check_property_value -q "this.snmp_contact" "${CONTACT}" \
    && check_property_value -q "this.snmp_location" "${LOCATION}" \
    && check_property_value -q "this.snmp_v3_password" "${PASSWORD}" \
    && echo_ok || (echo_fail && return 1)

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
snmp_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) snmp_tests ;;
     COMPLETE) snmp_tests ;;
    BENCHMARK) ;;
            *) snmp_tests ;;
  esac
}
