#!/usr/bin/env bash
# Author: Kris Moore
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="network"
export REQUIRES

# Run a series of tests on the ssh settings
# We also leave it enabled, so we have access to VM if something hangs / goes wrong
ssh_tests() {
  set_test_group_text "1 - Create - SSH Tests" "3"
  CLASSNAME=ixbuild.resty.functional.create.ssh

  echo_test_title "Configuring SSH settings"
  rest_request "PUT" "/services/ssh/" '{ "ssh_rootlogin": true }'
  check_rest_response "200 OK"

  echo_test_title "Enabling SSH Service"
  rest_request "PUT" "/services/services/ssh/" '{ "srv_enable": true }'
  check_rest_response "200 OK"

  echo_test_title "Checking to see if SSH service is enabled"
  rest_request "GET" "/services/services/ssh/"
  check_service_status "RUNNING"

}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
ssh_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) ssh_tests ;;
     COMPLETE) ssh_tests ;;
    BENCHMARK) ;;
            *) ssh_tests ;;
  esac
}
