#!/usr/local/bin/bash
# Author: Kris Moore
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="system"
export REQUIRES

storage_tests()
{
  # Set the group text and number of tests
  set_test_group_text "1 - Create - Storage tests" "45"
  CLASSNAME=ixbuild.resty.functional.create.storage

# Set the default VMBACKEND
if [ -z "$VMBACKEND" ] ; then
  VMBACKEND="vbox"
  echo $VMBACKEND
fi

# Determine which VM backend to use for storage
case ${VMBACKEND} in
  esxi)
    export disk1="da0"
    export disk2="da1"
    ;;
  vbox)
    export disk1="ada1"
    export disk2="ada2"
    ;;
esac

  # Check getting disks
  echo_test_title "Disks / API functionality"
  rest_request "GET" "/storage/disk/"
  check_rest_response "200 OK" || return 1

  # Check creating a zpool
  echo_test_title "Creating volume"
  rest_request "POST" "/storage/volume/" '{ "volume_name" : "tank", "layout" : [ { "vdevtype" : "stripe", "disks" : [ "'${disk1}'", "'${disk2}'" ] } ] }'
  check_rest_response "201 Created" || return 1

  # Check creating a dataset 01/20 /share
  echo_test_title "Creating dataset 01/20 tank/share"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "share" }'
  check_rest_response "201 Created" || return 1

  # Check creating a dataset 02/20 /jails
  echo_test_title "Creating dataset 02/20 tank/jails"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "jails" }'
  check_rest_response "201 Created" || return 1

  # Check creating a dataset 03/20
  echo_test_title "Creating dataset 03/20 tank/dataset03"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "dataset03" }'
  check_rest_response "201 Created" || return 1

  # Check creating a dataset 04/20
  echo_test_title "Creating dataset 04/20 tank/dataset04"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "dataset04" }'
  check_rest_response "201 Created" || return 1

  # Check creating a dataset 05/20
  echo_test_title "Creating dataset 05/20 tank/dataset05"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "dataset05" }'
  check_rest_response "201 Created" || return 1

  # Check creating a dataset 06/20
  echo_test_title "Creating dataset 06/20 tank/dataset06"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "dataset06" }'
  check_rest_response "201 Created" || return 1

  # Check creating a dataset 07/20
  echo_test_title "Creating dataset 07/20 tank/dataset07"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "dataset07" }'
  check_rest_response "201 Created" || return 1

  # Check creating a dataset 08/20
  echo_test_title "Creating dataset 08/20 tank/dataset08"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "dataset08" }'
  check_rest_response "201 Created" || return 1

  # Check creating a dataset 09/20
  echo_test_title "Creating dataset 09/20 tank/dataset09"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "dataset09" }'
  check_rest_response "201 Created" || return 1

  # Check creating a dataset 10/20
  echo_test_title "Creating dataset 10/20 tank/dataset10"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "dataset10" }'
  check_rest_response "201 Created" || return 1

  # Check creating a dataset 11/20
  echo_test_title "Creating dataset 11/20 tank/dataset11"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "dataset11" }'
  check_rest_response "201 Created" || return 1

  # Check creating a dataset 12/20
  echo_test_title "Creating dataset 12/20 tank/dataset12"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "dataset12" }'
  check_rest_response "201 Created" || return 1

  # Check creating a dataset 13/20
  echo_test_title "Creating dataset 13/20 tank/dataset13"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "dataset13" }'
  check_rest_response "201 Created" || return 1

  # Check creating a dataset 14/20
  echo_test_title "Creating dataset 14/20 tank/dataset14"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "dataset14" }'
  check_rest_response "201 Created" || return 1

  # Check creating a dataset 15/20
  echo_test_title "Creating dataset 15/20 tank/dataset15"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "dataset15" }'
  check_rest_response "201 Created" || return 1

  # Check creating a dataset 16/20
  echo_test_title "Creating dataset 16/20 tank/dataset16"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "dataset16" }'
  check_rest_response "201 Created" || return 1

  # Check creating a dataset 17/20
  echo_test_title "Creating dataset 17/20 tank/dataset17"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "dataset17" }'
  check_rest_response "201 Created" || return 1

  # Check creating a dataset 18/20
  echo_test_title "Creating dataset 18/20 tank/dataset18"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "dataset18" }'
  check_rest_response "201 Created" || return 1

  # Check creating a dataset 19/20
  echo_test_title "Creating dataset 19/20 tank/dataset19"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "dataset19" }'
  check_rest_response "201 Created" || return 1

  # Check creating a dataset 20/20
  echo_test_title "Creating dataset 20/20 tank/dataset20"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "dataset20" }'
  check_rest_response "201 Created" || return 1

  # Set the permissions of the dataset 01/20
  echo_test_title "Changing permissions on /mnt/tank/share"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank/share", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
  check_rest_response "201 Created" || return 1

  # Set the permissions of the dataset 02/20
  echo_test_title "Changing permissions on /mnt/tank/jails"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank/jails", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
  check_rest_response "201 Created" || return 1

  # Set the permissions of the dataset 03/20
  echo_test_title "Changing permissions on /mnt/tank/dataset03"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank/dataset03", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
  check_rest_response "201 Created" || return 1

  # Set the permissions of the dataset 04/20
  echo_test_title "Changing permissions on /mnt/tank/dataset04"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank/dataset04", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
  check_rest_response "201 Created" || return 1

  # Set the permissions of the dataset 05/20
  echo_test_title "Changing permissions on /mnt/tank/dataset05"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank/jails", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
  check_rest_response "201 Created" || return 1

  # Set the permissions of the dataset 06/20
  echo_test_title "Changing permissions on /mnt/tank/dataset06"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank/dataset06", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
  check_rest_response "201 Created" || return 1

  # Set the permissions of the dataset 07/20
  echo_test_title "Changing permissions on /mnt/tank/dataset07"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank/dataset07", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
  check_rest_response "201 Created" || return 1

  # Set the permissions of the dataset 08/20
  echo_test_title "Changing permissions on /mnt/tank/dataset08"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank/dataset08", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
  check_rest_response "201 Created" || return 1

  # Set the permissions of the dataset 09/20
  echo_test_title "Changing permissions on /mnt/tank/dataset09"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank/dataset09", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
  check_rest_response "201 Created" || return 1

  # Set the permissions of the dataset 10/20
  echo_test_title "Changing permissions on /mnt/tank/dataset10"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank/dataset11", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
  check_rest_response "201 Created" || return 1

  # Set the permissions of the dataset 11/20
  echo_test_title "Changing permissions on /mnt/tank/dataset11"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank/dataset11", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
  check_rest_response "201 Created" || return 1

  # Set the permissions of the dataset 12/20
  echo_test_title "Changing permissions on /mnt/tank/dataset12"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank/dataset12", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
  check_rest_response "201 Created" || return 1

  # Set the permissions of the dataset 13/20
  echo_test_title "Changing permissions on /mnt/tank/dataset13"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank/dataset13", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
  check_rest_response "201 Created" || return 1

  # Set the permissions of the dataset 14/20
  echo_test_title "Changing permissions on /mnt/tank/dataset14"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank/dataset14", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
  check_rest_response "201 Created" || return 1

  # Set the permissions of the dataset 15/20
  echo_test_title "Changing permissions on /mnt/tank/dataset15"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank/dataset15", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
  check_rest_response "201 Created" || return 1

  # Set the permissions of the dataset 16/20
  echo_test_title "Changing permissions on /mnt/tank/dataset16"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank/dataset16", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
  check_rest_response "201 Created" || return 1

  # Set the permissions of the dataset 17/20
  echo_test_title "Changing permissions on /mnt/tank/dataset17"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank/dataset17", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
  check_rest_response "201 Created" || return 1

  # Set the permissions of the dataset 18/20
  echo_test_title "Changing permissions on /mnt/tank/dataset18"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank/dataset18", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
  check_rest_response "201 Created" || return 1

  # Set the permissions of the dataset 19/20
  echo_test_title "Changing permissions on /mnt/tank/dataset19"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank/dataset19", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
  check_rest_response "201 Created" || return 1

  # Set the permissions of the dataset 20/20
  echo_test_title "Changing permissions on /mnt/tank/dataset20"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank/dataset20", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
  check_rest_response "201 Created" || return 1

  # Check creating a ZFS snapshot
  echo_test_title "Creating a ZFS snapshot tank@test"
  rest_request "POST" "/storage/snapshot/" '{ "dataset": "tank", "name": "test" }'
  check_rest_response "201 Created" || return 1

  # Create a dataset for testing snapshot
  echo_test_title "Creating dataset for testing snapshot rollback tank/snapcheck"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "snapcheck" }'
  check_rest_response "201 Created" || return 1

  # Check creating a ZVOL 1/2
  echo_test_title "Creating a ZVOL 1/2"
  rest_request "POST" "/storage/volume/tank/zvols/" '{ "name": "testzvol1", "volsize": "10M" }'
  check_rest_response "201" || return 1

  # Check creating a ZVOL 2/2
  echo_test_title "Creating a ZVOL 2/2"
  rest_request "POST" "/storage/volume/tank/zvols/" '{ "name": "testzvol2", "volsize": "10M" }'
  check_rest_response "201" || return 1

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
storage_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) storage_tests ; return $? ;;
     COMPLETE) storage_tests ; return $? ;;
    BENCHMARK) storage_tests ; return $? ;;
            *) storage_tests ; return $? ;;
  esac
}
