#!/usr/local/bin/bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES=""
export REQUIRES

system_tests() {
  set_test_group_text "1 - Create - System tests" "3"
  CLASSNAME=ixbuild.resty.functional.create.system

  # Get system version
  echo_test_title "Checking system version.."
  rest_request "GET" "/system/version/"
  check_rest_response "200 OK"

  # Set the timezone
  echo_test_title "Setting timezone.."
  rest_request "PUT" "/system/settings/" '{ "stg_timezone": "America/New_York" }'
  check_rest_response "200 OK"

  # Create loader tunable
  echo_test_title "Creating system tunable 'linux_load'.."
  rest_request "POST" "/system/tunable/" '{ "tun_var": "linux_load", "tun_enabled": true, "tun_value": "YES", "tun_type": "loader" }'
  check_rest_response "201 Created"

  # Check loader tunable
  echo_test_title "Checking system tunable 'linux_load'.."
  rest_request GET "/system/tunable/"
  check_rest_response "200 OK" || return 1
  TUNSTATUS=$(cat ${RESTYOUT} | ${JSAWK} 'return this.tun_var')
  echo "TUNSTATUS: $TUNSTATUS"
  echo $TUNSTATUS | grep -q 'linux_load'
  if [ $? -eq 0 ] ; then
    echo_ok
  else
    echo_fail
  fi
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
system_init()
{
  # Run all the tests
  case $TESTSET in
        SMOKE) system_tests ; return $? ;;
     COMPLETE) system_tests ; return $? ;;
    BENCHMARK) ;;
            *) system_tests ; return $? ;;
  esac
}
