#!/usr/bin/env bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES=""
export REQUIRES

ad_tests() 
{

  SMB_SHARE="TestShare"
  SMB_PATH="/mnt/tank/cifs"

  TEST_CNT=18
  if [ -n "${OSX_HOST}" -a -n "${BRIDGEIP}" ]; then
    TEST_CNT=21

    # Clean up any leftover items from previous failed SMB runs
    osx_test 'umount -f "/Volumes/'"${SMB_NAME}"'"; rmdir "/Volumes/'"${SMB_SHARE}"'"; exit 0'
  fi

  set_test_group_text "2 - Update - Active Directory tests" "20"
  CLASSNAME=ixbuild.resty.functional.update.ad

  if [ -z "$ADUSERNAME" -o -z "$ADPASSWORD" ] ; then
     echo -n "Missing the ADUSERNAME / ADPASSWORD settings, test skipped.."
     echo_skipped
     add_xml_result "skipped" "Skipped due to missing AD settings"
     return 0
  fi

  # Clean up any leftover items from previous failed AD LDAP or SMB runs
  rest_request "PUT" "/directoryservice/activedirectory/1/" '{ "ad_bindpw": "'${ADPASSWORD}'", "ad_bindname": "'${ADUSERNAME}'", "ad_domainname": "'${BRIDGEDOMAIN}'", "ad_netbiosname_a": "'${BRIDGEHOST}'", "ad_idmap_backend": "rid", "ad_enable":"false" }'
  rest_request "PUT" "/directoryservice/ldap/1/" '{ "ldap_basedn": "'${LDAPBASEDN}'", "ldap_binddn": "'${LDAPBINDDN}'",  "ldap_bindpw": "'${LDAPBINDPASSWORD}'", "ldap_netbiosname_a": "'${BRIDGEHOST}'", "ldap_hostname": "'${LDAPHOSTNAME}'", "ldap_has_samba_schema": true, "ldap_enable": false }'
  rest_request "PUT" "/services/services/cifs/" '{ "srv_enable": false }'
  rest_request "DELETE" "/sharing/cifs/" '{ "cfs_comment": "My Test CIFS Share", "cifs_path": "/mnt/tank/cifs", "cifs_name": "TestShare", "cifs_guestok": true, "cifs_vfsobjects": "streams_xattr" }'
  umount -A
  rmdir /tmp/cifs-mnt.*

  # Set auxilary parameters to allow mount_smbfs to work with ldap
  echo_test_title "Setting auxilary parameters for mount_smbfs.."
  rest_request "PUT" "/services/cifs/" '{ "cifs_srv_smb_options": "lanman auth = yes\nntlm auth = yes \nraw NTLMv2 auth = yes" }'
  check_rest_response "200 OK"

  # Enable Active Directory Directory
  echo_test_title "Enabling Active Directory.."
  rest_request "PUT" "/directoryservice/activedirectory/1/" '{ "ad_bindpw": "'${ADPASSWORD}'", "ad_bindname": "'${ADUSERNAME}'", "ad_domainname": "'${BRIDGEDOMAIN}'", "ad_netbiosname_a": "'${BRIDGEHOST}'", "ad_idmap_backend": "ad", "ad_enable":true }'
  check_rest_response "200 OK"

  # Check Active Directory
  echo_test_title "Checking Active Directory.."
  rest_request GET "/directoryservice/activedirectory/"
  check_property_value "return this.ad_enable" "true" || return 1

  echo_test_title "Checking to see if CIFS service is enabled"
  rest_request "GET" "/services/services/cifs/"
  check_service_status -q "RUNNING"
  check_exit_status -q && echo_ok || (
    echo_test_title "Enabling CIFS service"
    rest_request "PUT" "/services/cifs/" '{ "cifs_srv_description": "Test FreeNAS Server", "cifs_srv_guest": "nobody", "cifs_hostname_lookup": false, "cifs_srv_aio_enable": false }'
    check_rest_response "200 OK"

    # Now start the service
    echo_test_title "Starting CIFS service"
    rest_request "PUT" "/services/services/cifs/" '{ "srv_enable": true }'
    check_rest_response "200 OK"
  )

  echo_test_title "Changing permissions on /mnt/tank/cifs"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank/cifs", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "AD01\\QA", "mp_recursive": true }'
  check_rest_response "201 Created" 

  echo_test_title "Creating a CIFS share on /mnt/tank/cifs"
  rest_request "POST" "/sharing/cifs/" '{ "cfs_comment": "My Test CIFS Share", "cifs_path": "/mnt/tank/cifs", "cifs_name": "TestShare", "cifs_guestok": true, "cifs_vfsobjects": "streams_xattr" }'
  check_rest_response "201 Created"

  if [ -n "${OSX_HOST}" -a -n "${BRIDGEIP}" ]; then
    echo_test_title "Mounting CIFS as guest on OSX system and test write access"
    osx_test 'mkdir -p "/Volumes/'"${SMB_SHARE}"'" && mount -t smbfs "smb://guest@'"${BRIDGEIP}"'/'"${SMB_SHARE}"'" "/Volumes/'"${SMB_SHARE}"'" && touch "/Volumes/'"${SMB_SHARE}"'/testfile.txt"'
    check_exit_status || return 1

    echo_test_title "Moving CIFS test file into a new directory"
    osx_test 'mkdir -p "/Volumes/'"${SMB_SHARE}"'/tmp" && mv "/Volumes/'"${SMB_SHARE}"'/testfile.txt" "/Volumes/'"${SMB_SHARE}"'/tmp/testfile.txt"'
    check_exit_status || return 1

    echo_test_title "Deleting test file and directory from CIFS share"
    osx_test 'rm -f "/Volumes/'"${SMB_SHARE}"'/tmp/testfile.txt" && rmdir "/Volumes/'"${SMB_SHARE}"'/tmp" && find -- "/Volumes/'"${SMB_SHARE}"'/" -prune -type d -empty | grep -q .'
    check_exit_status || return 1

    echo_test_title "Unmount CIFS share"
    osx_test 'umount "/Volumes/'"${SMB_SHARE}"'"'
    check_exit_status || return 1
  fi

  # Disable Active Directory Directory
  echo_test_title "Disabling Active Directory.."
  rest_request "PUT" "/directoryservice/activedirectory/1/" '{ "ad_bindpw": "'${ADPASSWORD}'", "ad_bindname": "'${ADUSERNAME}'", "ad_domainname": "'${BRIDGEDOMAIN}'", "ad_netbiosname_a": "'${BRIDGEHOST}'", "ad_idmap_backend": "ad", "ad_enable":"false" }'
  check_rest_response "200 OK"

  # Check Active Directory
  echo_test_title "Verify Active Directory is disabled.."
  rest_request GET "/directoryservice/activedirectory/"
  check_property_value "return this.ad_enable" "false"

  echo_test_title "Verify CIFS service is disabled"
  rest_request "GET" "/services/services/cifs/"
  check_service_status "STOPPED"

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
ad_init()
{
  # Run all the tests
  case $TESTSET in
        SMOKE) ad_tests ; return $? ;;
     COMPLETE) ad_tests ; return $? ;;
    BENCHMARK) ;;
            *) ad_tests ; return $? ;;
  esac
}
