#!/usr/bin/env bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES=""
export REQUIRES

ad_bsd_tests()
{
  local DATASET="ad-bsd"
  local SMB_NAME="TestShare"
  local SMB_PATH="/mnt/tank/${DATASET}"
  local MOUNTPOINT="/tmp/ad-mnt.$$"
  local VOL_GROUP="ga"

  set_test_group_text "2 - Update - Active Directory BSD tests" "24"
  CLASSNAME=ixbuild.resty.functional.update.ad_bsd

  if [ -z "$ADUSERNAME" -o -z "$ADPASSWORD" ] ; then
     echo -n "Missing the ADUSERNAME / ADPASSWORD settings, test skipped.."
     echo_skipped
     add_xml_result "skipped" "Skipped due to missing AD settings"
     return 0
  fi

  # Clean up any leftover items from previous failed AD LDAP or SMB runs
  rest_request "PUT" "/directoryservice/activedirectory/1/" '{ "ad_bindpw": "'${ADPASSWORD}'", "ad_bindname": "'${ADUSERNAME}'", "ad_domainname": "'${BRIDGEDOMAIN}'", "ad_netbiosname_a": "'${BRIDGEHOST}'", "ad_idmap_backend": "rid", "ad_enable":"false" }'
  rest_request "PUT" "/directoryservice/ldap/1/" '{ "ldap_basedn": "'${LDAPBASEDN}'", "ldap_binddn": "'${LDAPBINDDN}'",  "ldap_bindpw": "'${LDAPBINDPASSWORD}'", "ldap_netbiosname_a": "'${BRIDGEHOST}'", "ldap_hostname": "'${LDAPHOSTNAME}'", "ldap_has_samba_schema": true, "ldap_enable": false }'
  rest_request "PUT" "/services/services/cifs/" '{ "srv_enable": false }'
  rest_request "DELETE" "/sharing/cifs/" '{ "cfs_comment": "My Test SMB Share", "cifs_path": "'"${SMB_PATH}"'", "cifs_name": "'"${SMB_NAME}"'", "cifs_guestok": true, "cifs_vfsobjects": "streams_xattr" }'
  rest_request "DELETE" "/storage/volume/1/datasets/${DATASET}/"
  umount -A &>/dev/null
  rmdir /tmp/ad-mnt.* &>/dev/null

  # Set auxilary parameters to allow mount_smbfs to work with Active Directory
  echo_test_title "Setting auxilary parameters for mount_smbfs.."
  rest_request "PUT" "/services/cifs/" '{ "cifs_srv_smb_options": "lanman auth = yes\nntlm auth = yes \nraw NTLMv2 auth = yes" }'
  check_rest_response "200 OK"

  echo_test_title "Creating SMB dataset"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "'"${DATASET}"'" }'
  check_rest_response "201 Created"

  # Enable Active Directory Directory
  echo_test_title "Enabling Active Directory.."
  rest_request "PUT" "/directoryservice/activedirectory/1/" '{ "ad_bindpw": "'${ADPASSWORD}'", "ad_bindname": "'${ADUSERNAME}'", "ad_domainname": "'${BRIDGEDOMAIN}'", "ad_netbiosname_a": "'${BRIDGEHOST}'", "ad_idmap_backend": "ad", "ad_enable":true }'
  check_rest_response "200 OK"

  # Check Active Directory
  echo_test_title "Checking Active Directory.."
  rest_request GET "/directoryservice/activedirectory/"
  check_property_value "return this.ad_enable" "true" || return 1

  echo_test_title "Checking to see if SMB service is enabled"
  rest_request "GET" "/services/services/cifs/"
  check_service_status -q "RUNNING"
  check_exit_status -q && echo_ok || (
    echo_test_title "Enabling SMB service"
    rest_request "PUT" "/services/cifs/" '{ "cifs_srv_description": "Test FreeNAS Server", "cifs_srv_guest": "nobody", "cifs_hostname_lookup": false, "cifs_srv_aio_enable": false }'
    check_rest_response "200 OK"

    # Now start the service
    echo_test_title "Starting SMB service"
    rest_request "PUT" "/services/services/cifs/" '{ "srv_enable": true }'
    check_rest_response "200 OK"
  )

  # Wait a moment for samba to spin up
  sleep 4

  echo_test_title "Changing permissions on ${SMB_PATH}"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "'"${SMB_PATH}"'", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "AD01\\QA", "mp_recursive": true }'
  check_rest_response "201 Created" 

  echo_test_title "Creating a SMB share on ${SMB_PATH}"
  rest_request "POST" "/sharing/cifs/" '{ "cfs_comment": "My Test SMB Share", "cifs_path": "'"${SMB_PATH}"'", "cifs_name": "'"${SMB_NAME}"'", "cifs_guestok": true, "cifs_vfsobjects": "streams_xattr" }'
  check_rest_response "201 Created"

  # Now check if we can mount SMB / create / rename / copy / delete / umount
  echo_test_title "Poll VM to ensure SMB service is up and running"
  wait_for_avail_port "445"
  check_exit_status || return 1

  echo_test_title "Creating SMB mountpoint"
  rc_test "mkdir -p '${MOUNTPOINT}'" || return 1
  sync

  # Store credentials file for mount_smb
  # The ADUSER user must exist in AD with this password
  echo "[TESTNAS:ADUSER]" > ~/.nsmbrc
  echo password=12345678 >> ~/.nsmbrc

  echo_test_title "Mounting SMB"
  rc_test "mount_smbfs -N -I ${ip} -W AD01 //aduser@testnas/${SMB_NAME} '${MOUNTPOINT}'" || return 1

  echo_test_title "Verify SMB share has been mounted"
  wait_for_bsd_mnt "${MOUNTPOINT}"
  check_exit_status || return 1

  local device_name=`dirname "${MOUNTPOINT}"`
  echo_test_title "Checking permissions on ${device_name}"
  rc_test "ls -la '${device_name}' | awk '\$4 == \"${VOL_GROUP}\" && \$9 == \"${DATASET}\" ' "

  echo_test_title "Creating SMB file"
  rc_test "touch ${MOUNTPOINT}/testfile" || return 1

  echo_test_title "Moving SMB file"
  rc_test "mv ${MOUNTPOINT}/testfile ${MOUNTPOINT}/testfile2" || return 1

  echo_test_title "Copying SMB file"
  rc_test "cp '${MOUNTPOINT}/testfile2' '${MOUNTPOINT}/testfile'" || return 1

  echo_test_title "Deleting SMB file 1/2"
  rc_test "rm '${MOUNTPOINT}/testfile'" || return 1

  echo_test_title "Deleting SMB file 2/2"
  rc_test "rm '${MOUNTPOINT}/testfile2'" || return 1

  echo_test_title "Unmounting SMB"
  rc_test "umount '${MOUNTPOINT}'" || return 1

  echo_test_title "Removing SMB mountpoint"
  rc_test "rmdir '${MOUNTPOINT}'" || return 1

  echo_test_title "Removing SMB share on ${SMB_PATH}"
  rest_request "DELETE" "/sharing/cifs/" '{ "cfs_comment": "My Test SMB Share", "cifs_path": "'"${SMB_PATH}"'", "cifs_name": "'"${SMB_NAME}"'", "cifs_guestok": true, "cifs_vfsobjects": "streams_xattr" }'
  check_rest_response "204"

  # Disable Active Directory Directory
  echo_test_title "Disabling Active Directory.."
  rest_request "PUT" "/directoryservice/activedirectory/1/" '{ "ad_bindpw": "'${ADPASSWORD}'", "ad_bindname": "'${ADUSERNAME}'", "ad_domainname": "'${BRIDGEDOMAIN}'", "ad_netbiosname_a": "'${BRIDGEHOST}'", "ad_idmap_backend": "ad", "ad_enable":"false" }'
  check_rest_response "200 OK"

  # Check Active Directory
  echo_test_title "Verify Active Directory is disabled.."
  rest_request GET "/directoryservice/activedirectory/"
  check_property_value "return this.ad_enable" "false"

  echo_test_title "Verify SMB service is disabled"
  rest_request "GET" "/services/services/cifs/"
  check_service_status "STOPPED"

  # Check destroying a SMB dataset
  echo_test_title "Destroying SMB dataset"
  rest_request "DELETE" "/storage/volume/1/datasets/${DATASET}/"
  check_rest_response "204" || return 1

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
ad_bsd_init()
{
  # Run all the tests
  case $TESTSET in
        SMOKE) ad_bsd_tests ; return $? ;;
     COMPLETE) ad_bsd_tests ; return $? ;;
    BENCHMARK) ;;
            *) ad_bsd_tests ; return $? ;;
  esac
}
