#!/usr/bin/env bash
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES=""
export REQUIRES

# $1 = Property name using JSAWK syntax
# $2 = Expected value
poll_for_property_value()
{
  INTERVAL_SECS=10
  INTERVAL_LOOPS=30

  loop_cnt=0
  while :
  do
    rest_request "GET" "/system/alert/"
    check_property_value -q "${1}" "${2}" && break

    loop_cnt=$(expr $loop_cnt + 1)
    if [ $loop_cnt -gt $INTERVAL_LOOPS ]; then
      echo -n " expected value not found."
      return 1
    fi
    echo -n "."
    sleep $INTERVAL_SECS
  done

  return 0
}

alerts_tests()
{
  ALERT_MSG="Testing system alerts with failure."

  set_test_group_text "2 - Update - System Alert tests" "2"
  CLASSNAME=ixbuild.resty.functional.update.alerts

  echo_test_title "Polling API endpoint for new system alert"
  poll_for_property_value "this.message" "${ALERT_MSG}"
  check_exit_status -q && echo_ok || return 1

  echo_test_title "Validating API alert values"
  check_property_value -q "this.level" "CRIT" && check_property_value "this.dismissed" "false" || return 1

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
alerts_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) alerts_tests ;;
     COMPLETE) alerts_tests ;;
    BENCHMARK) ;;
            *) alerts_tests ;;
  esac
}
