#!/usr/local/bin/bash
# Author: Kris Moore
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES=""
export REQUIRES

# Run a series of tests on the boot-environments
bootenv_tests() {
  set_test_group_text "1 - Update - Boot-Environment Tests" "1"

  echo_test_title "Cloning a new boot-environment: newbe1"
  rest_request "POST" "/system/bootenv/" '{ "name": "newbe1", "source": "default" }'
  check_rest_response "201 CREATED" || return 1

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
bootenv_init()
{
  # Run all the bootenv tests
  case $TESTSET in
        SMOKE) bootenv_tests ; return $? ;;
     COMPLETE) bootenv_tests ; return $? ;;
    BENCHMARK) ;;
            *) bootenv_tests ; return $? ;;
  esac
}

