#!/usr/bin/env bash
# License: BSD
# Location for tests into REST API of FreeNAS
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES=""
export REQUIRES

cronjob_tests()
{
  set_test_group_text "1 - Update - Cron tests" "4"
  CLASSNAME=ixbuild.resty.functional.delete.cronjob

  local TESTFILE="/tmp/.testFileCreatedViaCronjob"
  local CRONJOB_ID=1
  
  sleep 120

  # Ensure test file does exist
  echo_test_title "Verify cronjob has created the test file.."
  ssh_test "test -f ${TESTFILE}"
  check_exit_status || return 1

  # Update cronjob to disabled with new cron_command
  echo_test_title "Updating cron job status to disabled, updating command.."
  rest_request "PUT" "/tasks/cronjob/${CRONJOB_ID}/" '{ "cron_enabled": false }'
  check_rest_response "200 OK" || return 1

  # Check that cronjob is disabled
  echo_test_title "Checking that API reports the cronjob as updated.."
  rest_request "GET" "/tasks/cronjob/${CRONJOB_ID}/"
  check_property_value "return this.cron_enabled" "false" || return 1

  # Delete test file so we can verify it is no longer being created later in the delete/cronjob test
  echo_test_title "Deleting test file created by cronjob"
  ssh_test "rm -f ${TESTFILE}"
  check_exit_status || return 1

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
cronjob_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) cronjob_tests ;;
     COMPLETE) cronjob_tests ;;
    BENCHMARK) ;;
            *) cronjob_tests ;;
  esac
}
