#!/usr/local/bin/bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES=""
export REQUIRES

ftp_tests() {
  set_test_group_text "2 - Update - FTP tests" "4"
  CLASSNAME=ixbuild.resty.functional.update.ftp

  echo_test_title "Stopping ftp service"
  rest_request "PUT" "/services/services/ftp/" '{ "srv_enable": false }'
  check_rest_response "200 OK"


  echo_test_title "Updating ftp service"
  rest_request "PUT" "/services/ftp/" '{ "ftp_clients": 20 }'
  check_rest_response "200"

  echo_test_title "Starting ftp service"
  rest_request "PUT" "/services/services/ftp/" '{ "srv_enable": true }'
  check_rest_response "200 OK"

  echo_test_title "Checking to see if FTP service is enabled"
  rest_request "GET" "/services/services/ftp/"
  check_service_status "return this.srv_status" "RUNNING" || return 1

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
ftp_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) ftp_tests ;;
     COMPLETE) ftp_tests ;;
    BENCHMARK) ;;
            *) ftp_tests ;;
  esac
}
