#!/usr/bin/env bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES=""
export REQUIRES

group_tests() {
  set_test_group_text "2 - Update - Group tests" "1"
  CLASSNAME=ixbuild.resty.functional.update.group

  # Get the ID of testgroup
  echo_test_title "Fetching group id of previously created test group"
  if [ -f /tmp/.ixbuild_test_groupid -a -s /tmp/.ixbuild_test_groupid ] ; then
    groupid=`cat /tmp/.ixbuild_test_groupid`
    echo_ok
  else
    echo_fail && return 1
  fi

  # Update the testgroup
  echo_test_title "Updating group: testgroup"
  rest_request "PUT" "/account/groups/${groupid}/" '{ "bsdgrp_gid": "1201","bsdgrp_group": "newgroup" }'
  check_rest_response "200"

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
group_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) group_tests ;;
     COMPLETE) group_tests ;;
    BENCHMARK) ;;
            *) group_tests ;;
  esac
}
