#!/usr/bin/env bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES=""
export REQUIRES

ldap_tests() {
  set_test_group_text "2 - Update - LDAP tests" "22"
  CLASSNAME=ixbuild.resty.functional.update.ldap

  if [ -z "$LDAPBINDDN2" -o -z "$LDAPBINDPASSWORD2" ] ; then
     echo -n "Missing the LDAPBINDDN2 / LDAPBINDPASSWORD2 settings, test skipped.."
     echo_skipped
     add_xml_result "skipped" "Skipped due to missing LDAP settings"
     return 0
  fi

  # Clean up any leftover items from previous failed AD LDAP or SMB runs
  rest_request "PUT" "/directoryservice/activedirectory/1/" '{ "ad_bindpw": "'${ADPASSWORD}'", "ad_bindname": "'${ADUSERNAME}'", "ad_domainname": "'${BRIDGEDOMAIN}'", "ad_netbiosname_a": "'${BRIDGEHOST}'", "ad_idmap_backend": "rid", "ad_enable":"false" }'
  rest_request "PUT" "/directoryservice/ldap/1/" '{ "ldap_basedn": "'${LDAPBASEDN}'", "ldap_anonbind": false, "ldap_netbiosname_a": "'${BRIDGEHOST}'", "ldap_hostname": "'${LDAPHOSTNAME}'", "ldap_has_samba_schema": true, "ldap_enable": false }'
  rest_request "PUT" "/services/services/cifs/" '{ "srv_enable": false }'
  rest_request "DELETE" "/sharing/cifs/" '{ "cfs_comment": "My Test CIFS Share", "cifs_path": "/mnt/tank/cifs", "cifs_name": "TestShare", "cifs_guestok": true, "cifs_vfsobjects": "streams_xattr" }'

  # Set auxilary parameters to allow mount_smbfs to work with ldap
  echo_test_title "Set auxilary parameters for mount_smbfs.."
  rest_request "PUT" "/services/cifs/" '{ "cifs_srv_smb_options": "lanman auth = yes\nntlm auth = yes \nraw NTLMv2 auth = yes" }'
  check_rest_response "200 OK"

  # Enable LDAP
  echo_test_title "Enabling LDAP.."
  rest_request "PUT" "/directoryservice/ldap/1/" '{ "ldap_basedn": "'${LDAPBASEDN2}'", "ldap_binddn": "'${LDAPBINDDN2}'", "ldap_bindpw": "'${LDAPBINDPASSWORD2}'", "ldap_netbiosname_a": "'${BRIDGEHOST}'", "ldap_hostname": "'${LDAPHOSTNAME2}'", "ldap_has_samba_schema": true, "ldap_enable": true }'
  check_rest_response "200 OK"

  # Check LDAP
  echo_test_title "Checking LDAP.."
  rest_request GET "/directoryservice/ldap/"
  check_service_status "return this.ldap_enable" "true" || return 1

  echo_test_title "Checking to see if CIFS service is enabled"
  rest_request "GET" "/services/services/cifs/"
  check_service_status "return this.srv_state" "RUNNING"
  # check_exit_status || (
  if [ $? -ne 0 ] ; then
    echo_test_title "Enabling CIFS service"
    rest_request "PUT" "/services/cifs/" '{ "cifs_srv_description": "Test FreeNAS Server", "cifs_srv_guest": "nobody", "cifs_hostname_lookup": false, "cifs_srv_aio_enable": false }'
    check_rest_response "200 OK"

    # Now start the service
    echo_test_title "Starting CIFS service"
    rest_request "PUT" "/services/services/cifs/" '{ "srv_enable": true }'
    check_rest_response "200 OK"
  fi

  # Wait a moment for samba to spin up
  sleep 4

  # Now check if we can mount NFS / create / rename / copy / delete / umount
  echo_test_title "Creating CIFS mountpoint"
  rc_test "mkdir /tmp/cifs-mnt.$$" || return 1
  sync

  echo_test_title "Changing permissions on /mnt/tank/cifs"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "/mnt/tank/cifs", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "qa", "mp_recursive": true }'
  check_rest_response "201 Created"   

  echo_test_title "Creating a CIFS share on /mnt/tank/cifs"
  rest_request "POST" "/sharing/cifs/" '{ "cfs_comment": "My Test CIFS Share", "cifs_path": "/mnt/tank/cifs", "cifs_name": "TestShare", "cifs_guestok": true, "cifs_vfsobjects": "streams_xattr" }'
  check_rest_response "201 Created"

  sleep 10

  # Store credentials file for mount_smb
  # The LDAPUSER user must exist in LDAP with this password
  echo "[TESTNAS:LDAPUSER]" > ~/.nsmbrc
  echo password=12345678 >> ~/.nsmbrc

  echo_test_title "Mounting CIFS"
  rc_test "mount_smbfs -N -I ${ip} -W LDAP02 //ldapuser@testnas/TestShare /tmp/cifs-mnt.$$" "rmdir /tmp/cifs-mnt.$$" || return 1

  echo_test_title "Creating CIFS file"
  rc_test "touch /tmp/cifs-mnt.$$/testfile" "umount /tmp/cifs-mnt.$$ ; rmdir /tmp/cifs-mnt.$$" || return 1

  echo_test_title "Moving CIFS file"
  rc_test "mv /tmp/cifs-mnt.$$/testfile /tmp/cifs-mnt.$$/testfile2" || return 1

  echo_test_title "Copying CIFS file"
  rc_test "cp /tmp/cifs-mnt.$$/testfile2 /tmp/cifs-mnt.$$/testfile" || return 1

  echo_test_title "Deleting CIFS file 1/2"
  rc_test "rm /tmp/cifs-mnt.$$/testfile" || return 1

  echo_test_title "Deleting CIFS file 2/2"
  rc_test "rm /tmp/cifs-mnt.$$/testfile2" || return 1

  echo_test_title "Unmounting CIFS"
  rc_test "umount /tmp/cifs-mnt.$$" || return 1

  echo_test_title "Removing CIFS mountpoint"
  rc_test "rmdir /tmp/cifs-mnt.$$" || return 1

  echo_test_title "Removing CIFS share on /mnt/tank/cifs"
  rest_request "DELETE" "/sharing/cifs/" '{ "cfs_comment": "My Test CIFS Share", "cifs_path": "/mnt/tank/cifs", "cifs_name": "TestShare", "cifs_guestok": true, "cifs_vfsobjects": "streams_xattr" }'
  check_rest_response "204"

  # Disable LDAP
  echo_test_title "Disabling LDAP.."
  rest_request "PUT" "/directoryservice/ldap/1/" '{ "ldap_basedn": "'${LDAPBASEDN2}'", "ldap_binddn": "'${LDAPBINDDN2}'", "ldap_bindpw": "'${LDAPBINDPASSWORD2}'", "ldap_netbiosname_a": "'${BRIDGEHOST}'", "ldap_hostname": "'${LDAPHOSTNAME2}'", "ldap_has_samba_schema": true, "ldap_enable": false }'
  check_rest_response "200 OK"

  # Now stop the SMB service
  echo_test_title "Stopping CIFS service"
  rest_request "PUT" "/services/services/cifs/" '{ "srv_enable": false }'
  check_rest_response "200 OK"

  # Check LDAP
  echo_test_title "Verify LDAP is disabled.."
  rest_request GET "/directoryservice/ldap/"
  check_service_status "return this.ldap_enable" "false" || return 1

  echo_test_title "Verify CIFS service is disabled"
  rest_request "GET" "/services/services/cifs/"
  check_service_status "return this.srv_enable" "false" || return 1

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
ldap_init()
{
  # Run all the tests
  case $TESTSET in
        SMOKE) ldap_tests ; return $? ;;
     COMPLETE) ldap_tests ; return $? ;;
    BENCHMARK) ;;
            *) ldap_tests ; return $? ;;
  esac
}
