#!/usr/bin/env bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES=""
export REQUIRES

ldap_osx_tests()
{
  set_test_group_text "2 - Update - LDAP OS X tests" "25"
  CLASSNAME=ixbuild.resty.functional.update.ldap_osx

  local DATASET="ldap-osx"
  local SMB_NAME="TestShare"
  local SMB_PATH="/mnt/tank/${DATASET}"
  local MOUNTPOINT="/tmp/ldap-osx${BRIDGEHOST}"
  local LDAP_USER="ldapuser"
  local LDAP_PASS="12345678"
  local MP_GROUP="qa"

  local REQUIRED_SETTINGS=( \
    "OSX_HOST" "OSX_USERNAME" "OSX_PASSWORD" "BRIDGEIP" "BRIDGEHOST" \
    "ADUSERNAME" "ADPASSWORD" "LDAPBINDDN" "LDAPBINDPASSWORD" "LDAPBINDDN2" "LDAPBINDPASSWORD2" \
  )
  for SETTING in "${REQUIRED_SETTINGS[@]}"
  do
    if [ -z "${!SETTING}" ]; then
      echo -n "Required settings for ldap_osx: '${REQUIRED_SETTINGS[*]}'; missing ${SETTING}"
      echo_skipped
      return 0
    fi
  done

  # Clean up any leftover items from previous failed AD LDAP or SMB runs
  osx_test "diskutil unmount force \"${MOUNTPOINT}\"; rmdir \"${MOUNTPOINT}\"; exit 0"
  rest_request "PUT" "/directoryservice/activedirectory/1/" '{ "ad_bindpw": "'${ADPASSWORD}'", "ad_bindname": "'${ADUSERNAME}'", "ad_domainname": "'${BRIDGEDOMAIN}'", "ad_netbiosname_a": "'${BRIDGEHOST}'", "ad_idmap_backend": "rid", "ad_enable":"false" }'
  rest_request "PUT" "/directoryservice/ldap/1/" '{ "ldap_basedn": "'${LDAPBASEDN}'", "ldap_anonbind": false, "ldap_netbiosname_a": "'${BRIDGEHOST}'", "ldap_hostname": "'${LDAPHOSTNAME}'", "ldap_has_samba_schema": true, "ldap_enable": false }'
  rest_request "PUT" "/services/services/cifs/" '{ "srv_enable": false }'
  rest_request "DELETE" "/sharing/cifs/" '{ "cfs_comment": "My Test SMB Share", "cifs_path": "'"${SMB_PATH}"'", "cifs_name": "'"${SMB_NAME}"'", "cifs_guestok": true, "cifs_vfsobjects": "streams_xattr" }'
  rest_request "DELETE" "/storage/volume/1/datasets/${DATASET}/"

  # Set auxilary parameters to allow mount_smbfs to work with Active Directory
  echo_test_title "Setting auxilary parameters for mount_smbfs.."
  rest_request "PUT" "/services/cifs/" '{ "cifs_srv_smb_options": "lanman auth = no\nntlm auth = no \nraw NTLMv2 auth = no" }'
  check_rest_response "200 OK"

  echo_test_title "Creating SMB dataset"
  rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "'"${DATASET}"'" }'
  check_rest_response "201 Created" || return 1

  # Enable LDAP
  echo_test_title "Enabling LDAP.."
  rest_request "PUT" "/directoryservice/ldap/1/" '{ "ldap_basedn": "'${LDAPBASEDN2}'", "ldap_binddn": "'${LDAPBINDDN2}'", "ldap_bindpw": "'${LDAPBINDPASSWORD2}'", "ldap_netbiosname_a": "'${BRIDGEHOST}'", "ldap_hostname": "'${LDAPHOSTNAME2}'", "ldap_has_samba_schema": true, "ldap_enable": true }'
  check_rest_response "200 OK" || return 1

  # Check LDAP
  echo_test_title "Checking LDAP.."
  rest_request "GET" "/directoryservice/ldap/"
  check_property_value "return this.ldap_enable" "true" || return 1

  echo_test_title "Enabling SMB service"
  rest_request "PUT" "/services/cifs/" '{ "cifs_srv_description": "Test FreeNAS Server", "cifs_srv_guest": "nobody", "cifs_hostname_lookup": false, "cifs_srv_aio_enable": false }'
  check_rest_response "200 OK" || return 1

  # Now start the service
  echo_test_title "Starting SMB service"
  rest_request "PUT" "/services/services/cifs/" '{ "srv_enable": true }'
  check_rest_response "200 OK" || return 1

  echo_test_title "Verifying that SMB service has started"
  wait_for_avail_port "445"
  check_exit_status || return 1

  echo_test_title "Checking to see if SMB service is enabled"
  rest_request "GET" "/services/services/cifs/"
  check_service_status "RUNNING" || return 1

  echo_test_title "Changing permissions on ${SMB_PATH}"
  rest_request "PUT" "/storage/permission/" '{ "mp_path": "'"${SMB_PATH}"'", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "'${MP_GROUP}'", "mp_recursive": true }'
  check_rest_response "201 Created"

  echo_test_title "Creating a SMB share on ${SMB_PATH}"
  rest_request "POST" "/sharing/cifs/" '{ "cfs_comment": "My Test SMB Share", "cifs_path": "'"${SMB_PATH}"'", "cifs_name": "'"${SMB_NAME}"'", "cifs_guestok": true, "cifs_vfsobjects": "streams_xattr" }'
  check_rest_response "201 Created" || return 1

  #echo_test_title "Checking permissions on ${SMB_PATH}"
  #check_dataset_group "${SMB_PATH}" "${MP_GROUP}" || return 1

  if [ -n "${OSX_HOST}" -a -n "${BRIDGEIP}" ]; then
    # Mount share on OSX system and create a test file
    echo_test_title "Create mount-point for SMB on OSX system"
    osx_test "mkdir -p '${MOUNTPOINT}' && sync"
    check_exit_status || return 1

    echo_test_title "Mount SMB share on OSX system"
    osx_test "mount -t smbfs 'smb://${LDAP_USER}:${LDAP_PASS}@${BRIDGEIP}/${SMB_NAME}' '${MOUNTPOINT}'"
    check_exit_status || return 1

    echo_test_title "Verify SMB share mounted on OSX system"
    wait_for_osx_mnt "${MOUNTPOINT}"
    check_exit_status || return 1

    echo_test_title "Checking for ability to list files on ${MOUNTPOINT}"
    osx_test "time ls -la \"${MOUNTPOINT}\""
    check_exit_status || return 1

    echo_test_title "Create file on SMB share via OSX to test permissions"
    osx_test "touch '${MOUNTPOINT}/testfile.txt'"
    check_exit_status || return 1

    # Move test file to a new location on the SMB share
    echo_test_title "Moving SMB test file into a new directory"
    osx_test "mkdir -p '${MOUNTPOINT}/tmp' && mv '${MOUNTPOINT}/testfile.txt' '${MOUNTPOINT}/tmp/testfile.txt'"
    check_exit_status || return 1

    # Delete test file and test directory from SMB share
    echo_test_title "Deleting test file and directory from SMB share"
    osx_test "rm -f '${MOUNTPOINT}/tmp/testfile.txt' && rmdir '${MOUNTPOINT}/tmp'"
    check_exit_status || return 1

    echo_test_title "Verifying that test file and directory were successfully removed"
    osx_test "find -- '${MOUNTPOINT}/' -prune -type d -empty | grep -q ."
    check_exit_status || return 1

    # Clean up mounted SMB share
    # OS X `umount` manpage reports that umount may fail often.
    # "It is recommended that diskutil(1) (as in, ``diskutil unmount /mnt'') be used instead."
    echo_test_title "Unmount SMB share"
    osx_test "diskutil unmount force '${MOUNTPOINT}'"
    check_exit_status || return 1
  fi

  # Disable LDAP
  echo_test_title "Disabling LDAP.."
  rest_request "PUT" "/directoryservice/ldap/1/" '{ "ldap_basedn": "'${LDAPBASEDN2}'", "ldap_binddn": "'${LDAPBINDDN2}'", "ldap_bindpw": "'${LDAPBINDPASSWORD2}'", "ldap_netbiosname_a": "'${BRIDGEHOST}'", "ldap_hostname": "'${LDAPHOSTNAME2}'", "ldap_has_samba_schema": true, "ldap_enable": false }'
  check_rest_response "200 OK"

  # Now stop the SMB service
  echo_test_title "Stopping SMB service"
  rest_request "PUT" "/services/services/cifs/" '{ "srv_enable": false }'
  check_rest_response "200 OK"

  # Check LDAP
  echo_test_title "Verify LDAP is disabled.."
  rest_request "GET" "/directoryservice/ldap/"
  check_property_value "return this.ldap_enable" "false" || return 1

  echo_test_title "Verify SMB service has shut down"
  rest_request "GET" "/services/services/cifs/"
  check_service_status "STOPPED" || return 1

  # Check destroying a SMB dataset
  echo_test_title "Destroying SMB dataset"
  rest_request "DELETE" "/storage/volume/1/datasets/${DATASET}/"
  check_rest_response "204" || return 1

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
ldap_osx_init()
{
  # Run all the tests
  case $TESTSET in
        SMOKE) ldap_osx_tests ; return $? ;;
     COMPLETE) ldap_osx_tests ; return $? ;;
    BENCHMARK) ;;
            *) ldap_osx_tests ; return $? ;;
  esac
}
