#!/usr/local/bin/bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES=""
export REQUIRES

nfs_tests()
{
  # Set the group text and number of tests
  set_test_group_text "2 - Update - NFS tests" "2"
  CLASSNAME=ixbuild.resty.functional.update.nfs

  # Update NFS server
  echo_test_title "Updating the NFS service"
  rest_request "PUT" "/services/nfs/" '{ "nfs_srv_servers": "50" }'
  check_rest_response "200"

  echo_test_title "Checking to see if NFS service is enabled"
  rest_request "GET" "/services/services/nfs/"
  check_service_status "return this.srv_state" "RUNNING"

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
nfs_init()
{
  # Run all the nfs tests
  case $TESTSET in
        SMOKE) nfs_tests ;;
     COMPLETE) nfs_tests ;;
    BENCHMARK) ;;
            *) nfs_tests ;;
  esac
}

