#!/usr/local/bin/bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES=""
export REQUIRES

rsync_tests() {
  set_test_group_text "2 - Update - RSYNC tests" "2"
  CLASSNAME=ixbuild.resty.functional.update.rsync

  echo_test_title "Updating rsync resource"
  rest_request "PUT" "/services/rsyncmod/1/" '{ "rsyncmod_user": "testuser" }'
  check_rest_response "200"

  echo_test_title "Checking to see if rsync service is enabled"
  rest_request "GET" "/services/services/rsync/"
  check_rest_response "200 OK" || return 1  
  RSYNCSTATUS=$(cat ${RESTYOUT} | ${JSAWK} 'return this.srv_state')
  echo "RSYNCSTATUS: $RSYNCSTATUS"
  echo $RSYNCSTATUS | grep -q 'RUNNING'
  if [ $? -eq 0 ] ; then
    echo_ok
  else
    echo_fail
  fi

}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
rsync_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) rsync_tests ;;
     COMPLETE) rsync_tests ;;
    BENCHMARK) ;;
            *) rsync_tests ;;
  esac
}
