#!/usr/local/bin/bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="ssh"
export REQUIRES

storage_tests()
{
  # Set the group text and number of tests
  set_test_group_text "1 - Update - Storage tests" "1"

  # Check updating a ZVOL
  echo_test_title "Updating ZVOL"
  rest_request "PUT" "/storage/volume/tank/zvols/testzvol/" '{ "volsize" : "20485760" }'
  check_rest_response "201" || return 1

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
storage_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) storage_tests ; return $? ;;
     COMPLETE) storage_tests ; return $? ;;
    BENCHMARK) storage_tests ; return $? ;;
            *) storage_tests ; return $? ;;
  esac
}
