#!/usr/local/bin/bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS 9.10
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES=""
export REQUIRES

update_storage_tests()
{
  # Set the group text and number of tests
  set_test_group_text "2 - Update - Storage tests" "1"

  # Check updating a ZVOL
  echo_test_title "Updating ZVOL"
  rest_request "PUT" "/storage/volume/tank/zvols/testzvol/" '{ "volsize" : "50M" }'
  check_rest_response "201" || return 1

  # Check rolling back a ZFS snapshot
  echo_test_title "Rolling back ZFS snapshot tank@test"
  rest_request "POST" "/storage/snapshot/tank@test/rollback/" '{ "force": true }'
  check_rest_response "202" || return 1

  # Check to verify snapshot was rolled back
  "GET" "/storage/volume/tank/datasets/"
  check_rest_response "200 OK" || return 1
  SNAPSTATUS=$(cat ${RESTYOUT} | ${JSAWK} 'return this.name')
  echo "SNAPSTATUS: $SNAPSTATUS"
  echo $SNAPSTATUS | grep -q 'snapcheck'
  if [ $? -eq 0 ] ; then
    echo_fail
  else
    echo_ok
  fi

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
update_storage_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) update_storage_tests ; return $? ;;
     COMPLETE) update_storage_tests ; return $? ;;
    BENCHMARK) update_storage_tests ; return $? ;;
            *) update_storage_tests ; return $? ;;
  esac
}
