#!/usr/bin/env bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES=""
export REQUIRES

user_tests() {
  set_test_group_text "2 - Update - User tests" "3"
  CLASSNAME=ixbuild.resty.functional.update.user

  # Get the ID of testuser
  echo_test_title "Fetching user id of previously added test user"
  if [ -f /tmp/.ixbuild_test_userid -a -s /tmp/.ixbuild_test_userid ] ; then
    userid=`cat /tmp/.ixbuild_test_userid`
    echo_ok
  else
    echo_fail && return 1
  fi

  # Update the testuser
  echo_test_title "Updating user: testuser"
  rest_request "PUT" "/account/users/${userid}/" '{ "bsdusr_username": "testuser", "bsdusr_full_name": "Test Renamed", "bsdusr_password": "testing123", "bsdusr_uid": 1112, "bsdusr_home": "/mnt/tank/testuser", "bsdusr_mode": "755", "bsdusr_shell": "/bin/csh" }'
  check_rest_response "200"

  # Update password for testuser
  echo_test_title "Updating password for testuser"
  rest_request "POST" "/account/users/${userid}/password/" '{ "bsdusr_password": "newpasswd" }'
  check_rest_response "200"

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
user_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) user_tests ;;
     COMPLETE) user_tests ;;
    BENCHMARK) ;;
            *) user_tests ;;
  esac
}
