#!/usr/bin/env bash
# Author: Joe Maloney
# License: BSD
# Location for tests into REST API of FreeNAS
# Resty Docs: https://github.com/micha/resty
# jsawk: https://github.com/micha/jsawk

# List the other modules which must be run before this module can execute
REQUIRES="bootenv iscsi user group rsync"
export REQUIRES

storage_tests()
{
  # Set the group text and number of tests
  set_test_group_text "3 - Delete - Storage tests" "21"
  CLASSNAME=ixbuild.resty.functional.delete.storage

  # Check destroying a ZFS snapshot
  echo_test_title "Destroying ZFS snapshot tank@test"
  rest_request "DELETE" "/storage/snapshot/tank@test/"
  check_rest_response "204" || return 1

  # Check destroying a ZVOL 1/2
  echo_test_title "Destroying ZVOL 01/20"
  rest_request "DELETE" "/storage/volume/tank/zvols/testzvol1/"
  check_rest_response "204" || return 1

  # Check destroying a ZVOL 2/2
  echo_test_title "Destroying ZVOL 02/20"
  rest_request "DELETE" "/storage/volume/tank/zvols/testzvol2/"
  check_rest_response "204" || return 1

  local DATASET_CNT=20
  for count in $(seq -f "%02g" 3 $DATASET_CNT)
  do
    echo_test_title "Destroying dataset ${count}/${DATASET_CNT}"
    rest_request "DELETE" "/storage/volume/1/datasets/dataset${count}/"
    check_rest_response "204" || return 1
  done

  return 0
}

# Init function, this is called after module is sourced
# Pre-Set variables
# TESTSET = ( SMOKE / COMPLETE / BENCHMARK )
storage_init()
{
  # Run all the storage tests
  case $TESTSET in
        SMOKE) storage_tests ; return $? ;;
     COMPLETE) storage_tests ; return $? ;;
    BENCHMARK) storage_tests ; return $? ;;
            *) storage_tests ; return $? ;;
  esac
}
